# Cấu hình CSDL SQL Server
DB_TYPE=sqlserver
DB_URL=jdbc:sqlserver://localhost:1433;databaseName=KTQT_WebDB;encrypt=true;trustServerCertificate=true
DB_USER=sa
DB_PASSWORD=123
DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
DB_DIALECT=org.hibernate.dialect.SQLServerDialect

# SMTP Gmail
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=utemall.otp@gmail.com
SMTP_PASSWORD=qqap aogh fogt iipv
